const DATA_URL = "prep/mtech_cse_ktu_2026_resource_registry.json";
const state = { data: null, query: "", activeFilter: "All" };
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

function getSaved(key) { try { return JSON.parse(localStorage.getItem(key)) || []; } catch { return []; } }
function setSaved(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function courseId(course) { return `${semesterFor(course)}-${course.code}`.toLowerCase().replace(/[^a-z0-9-]/g, ""); }
function semesterFor(course) { if (course.code.startsWith("221")) return 1; if (course.code.startsWith("222")) return 2; if (course.code.startsWith("223")) return 3; if (course.code.startsWith("224")) return 4; return 3; }
function typeFor(course) { if (course.type) return course.type; if (course.code.includes("TCS")) return "Core"; if (course.code.includes("ECS")) return "Elective"; return "Course"; }
function titleCase(value = "") { return value.toLowerCase().replace(/\b\w/g, c => c.toUpperCase()); }
function modulesFor(course) { return (course.modules || []).map((raw, index) => { const match = raw.match(/^(Module[-\s]*\d+\s*(?:\([^)]*\)|:[^\n]*?)(?=\s(?:\d+\s*hours|[A-Z]))|Module\s*\d+\s*:[^\n]*?)(?:\s+\d+\s*hours)?\s*/i); const title = match ? match[1].replace(/\s+/g, " ").trim() : `Module ${index + 1}`; const body = raw.slice(match ? match[0].length : 0).replace(/\s+/g, " ").trim(); const topics = body.split(/\.|;|\s[-–]\s/).map(t => t.trim()).filter(t => t.length > 3).slice(0, 8); return { id: `${courseId(course)}-m${index + 1}`, title, body, topics }; }); }
function resourcesFor(course) { const r = course.resources || {}; return [...(r.notes || []).map(x => ({ ...x, kind: "Notes" })), ...(r.lectures || []).map(x => ({ ...x, kind: "Lecture" }))]; }
function progressKeys() { return getSaved("mtech-compass-complete"); }
function courseProgress(course) { const modules = modulesFor(course); const done = progressKeys(); const total = modules.reduce((sum, m) => sum + m.topics.length, 0); const completed = modules.reduce((sum, m) => sum + m.topics.filter((_, i) => done.includes(`${m.id}-t${i}`)).length, 0); return { total, completed, pct: total ? Math.round(completed / total * 100) : 0 }; }
function overallProgress() { const courses = state.data.courses; const totals = courses.map(courseProgress); const t = totals.reduce((a, x) => a + x.total, 0), c = totals.reduce((a, x) => a + x.completed, 0); return t ? Math.round(c / t * 100) : 0; }
function breadcrumb(items) { return `<div class="breadcrumb"><a href="#/">Home</a>${items.map(i => ` <span>›</span> ${i.href ? `<a href="${i.href}">${i.label}</a>` : i.label}`).join("")}</div>`; }
function toast(message) { const el = document.createElement("div"); el.className = "toast"; el.textContent = message; document.body.append(el); setTimeout(() => el.remove(), 2200); }
function bookmarkButton(course) { const saved = getSaved("mtech-compass-bookmarks"); const id = courseId(course), active = saved.includes(id); return `<button class="bookmark-button" data-bookmark="${id}" aria-label="${active ? "Remove" : "Save"} ${course.name}">${active ? "★" : "☆"}</button>`; }
function bindBookmarks() { $$('[data-bookmark]').forEach(button => button.addEventListener("click", e => { e.preventDefault(); e.stopPropagation(); const saved = getSaved("mtech-compass-bookmarks"), id = button.dataset.bookmark; const next = saved.includes(id) ? saved.filter(x => x !== id) : [...saved, id]; setSaved("mtech-compass-bookmarks", next); toast(saved.includes(id) ? "Removed from saved courses" : "Saved for later"); render(); })); }
function courseCard(course) { const p = courseProgress(course); return `<a class="course-card" href="#/course/${courseId(course)}"><span class="code">${course.code}</span>${bookmarkButton(course)}<h3>${titleCase(course.name)}</h3><span class="meta">${typeFor(course)} · ${modulesFor(course).length || "Project"} ${modulesFor(course).length === 1 ? "module" : "modules"} · ${p.pct}% complete</span></a>`; }
function layout(content, nav = "") { $("#app").innerHTML = content; $$("[data-nav]").forEach(a => a.classList.toggle("active", a.dataset.nav === nav)); bindBookmarks(); bindTopicButtons(); }
function home() { const progress = overallProgress(); const courses = state.data.courses; const sems = [1,2,3,4]; const first = courses.find(c => modulesFor(c).some(m => m.topics.length)); const p = first ? courseProgress(first) : { completed: 0, total: 0 }; layout(`<section class="hero"><div><p class="eyebrow">KTU · M.Tech CSE</p><h1>Your syllabus,<br><em>made navigable.</em></h1><p class="hero-copy">Find a topic, open the right academic resource, and keep one calm record of your progress across the M.Tech journey.</p><div class="search-box"><input id="global-search" autocomplete="off" placeholder="Search PCA, 222TCS100, MongoDB…" value="${state.query}"><span class="search-icon">⌕</span></div></div><aside class="progress-orb"><small>Learning progress</small><strong>${progress}<sup>%</sup></strong><p>Tracked across every topic you’ve marked complete.</p></aside></section>${state.query ? searchSection(state.query) : ""}<section><div class="section-head"><h2>Choose a semester</h2><a href="#/library">Browse all courses →</a></div><div class="semester-grid">${sems.map(s => { const n = courses.filter(c => semesterFor(c) === s).length; return `<a class="semester-card" href="#/semester/${s}"><span class="semester-number">0${s}</span><strong>Semester ${s}</strong><span class="course-count">${n ? `${n} learning paths` : "Research & completion"}</span></a>`; }).join("")}</div></section>${first ? `<section><div class="section-head"><h2>Continue learning</h2></div><article class="continue-card"><span class="module-pill">${first.code}</span><div><strong>${titleCase(first.name)}</strong><p>${p.completed ? `${p.completed} topics completed` : "Begin with your first module"} · ${p.pct}% complete</p></div><a href="#/course/${courseId(first)}">Open course →</a></article></section>` : ""}`, "home"); $("#global-search")?.addEventListener("input", e => { state.query = e.target.value; render(); }); }
function searchSection(query) { const q = query.toLowerCase().trim(); const hits = state.data.courses.filter(c => [c.code,c.name,...modulesFor(c).flatMap(m => [m.title,m.body,...m.topics])].join(" ").toLowerCase().includes(q)).slice(0,9); return `<section class="search-results"><div class="section-head"><h2>${hits.length ? `Results for “${query}”` : `Nothing found for “${query}”`}</h2></div>${hits.length ? hits.map(c => `<a class="result-row" href="#/course/${courseId(c)}"><div><small>${c.code} · Semester ${semesterFor(c)}</small><h3>${titleCase(c.name)}</h3><p>${modulesFor(c).flatMap(m => m.topics).filter(t => t.toLowerCase().includes(q)).slice(0,3).join(" · ") || "Course-level match"}</p></div><span>→</span></a>`).join("") : `<p class="empty">Try a course code, subject, module, topic, or resource provider.</p>`}</section>`; }
function library(semester = null) { const all = state.data.courses.filter(c => !semester || semesterFor(c) === Number(semester)); const filters = ["All", "Core", "Elective", "laboratory", "project", "research"]; const visible = state.activeFilter === "All" ? all : all.filter(c => typeFor(c).toLowerCase() === state.activeFilter.toLowerCase()); const label = semester ? `Semester ${semester}` : "Course library"; layout(`${breadcrumb(semester ? [{label:"Library",href:"#/library"},{label}] : [{label}])}<div class="page-top"><div><p class="eyebrow">Curriculum navigator</p><h1 class="page-title">${label}</h1><p class="page-description">Exact course modules from the verified KTU syllabus, paired with curated public learning resources.</p></div></div><div class="tabs">${filters.map(f => `<button class="tab ${state.activeFilter === f ? "active" : ""}" data-filter="${f}">${f === "laboratory" ? "Labs" : titleCase(f)}</button>`).join("")}</div><div class="course-list">${visible.length ? visible.map(courseCard).join("") : `<p class="empty">No ${state.activeFilter.toLowerCase()} courses in this view yet.</p>`}</div>`, "library"); $$('[data-filter]').forEach(b => b.addEventListener("click", () => { state.activeFilter = b.dataset.filter; render(); })); }
function coursePage(id) { const course = state.data.courses.find(c => courseId(c) === id); if (!course) return notFound(); const modules = modulesFor(course), resources = resourcesFor(course), p = courseProgress(course); const resourceButtons = resources.slice(0,2).map(r => `<a class="button ${r.kind === "Notes" ? "" : "ghost"}" href="${r.url}" target="_blank" rel="noreferrer">${r.kind === "Notes" ? "Open notes" : "Watch lectures"} ↗</a>`).join(""); layout(`${breadcrumb([{label:`Semester ${semesterFor(course)}`,href:`#/semester/${semesterFor(course)}`},{label:titleCase(course.name)}])}<div class="course-layout"><section><div class="course-heading"><span class="course-code">${course.code} · ${titleCase(typeFor(course))}</span><h1>${titleCase(course.name)}</h1><p class="page-description">${course.curation_note || "Curated resources matched to the official course syllabus."}</p><div class="course-actions">${resourceButtons}${bookmarkButton(course)}</div></div><div class="section-head"><h2>Modules</h2><span class="course-code">${modules.length} in syllabus</span></div><div class="module-list">${modules.length ? modules.map((m, mi) => moduleItem(course,m,mi,resources)).join("") : `<p class="empty">This project-style course has no taught modules. Its resources are ready above.</p>`}</div></section><aside class="side-panel"><p class="eyebrow">Course progress</p><h3>${p.pct}% complete</h3><div class="mini-progress"><span style="width:${p.pct}%"></span></div><p style="margin-top:11px">${p.completed} of ${p.total} syllabus topics marked complete.</p><p><strong>Why these resources?</strong><br>${course.curation_note || "They are the best currently curated matches."}</p></aside></div>`, "library"); }
function moduleItem(course, module, mi, resources) { const done = progressKeys(); const topicHtml = module.topics.length ? module.topics.map((topic, ti) => `<li><button class="${done.includes(`${module.id}-t${ti}`) ? "done" : ""}" data-topic="${module.id}-t${ti}" title="Mark topic complete">${topic}</button></li>`).join("") : `<li><span class="course-code">Topic detail pending curation</span></li>`; return `<details class="module" ${mi === 0 ? "open" : ""}><summary><span class="module-name">${module.title}</span><span class="course-code">${module.topics.length} topics</span></summary><p class="module-topics">${module.body}</p><ul class="topic-list">${topicHtml}</ul><div class="module-resources">${resources.length ? resources.map(r => `<a class="resource-card" href="${r.url}" target="_blank" rel="noreferrer"><span class="resource-kind">${r.kind}</span><span class="resource-title">${r.title}</span><span class="resource-arrow">↗</span></a>`).join("") : `<span class="course-code">Resource not curated yet</span>`}</div></details>`; }
function bindTopicButtons() { $$('[data-topic]').forEach(button => button.addEventListener("click", () => { const done = progressKeys(), id = button.dataset.topic; setSaved("mtech-compass-complete", done.includes(id) ? done.filter(x => x !== id) : [...done,id]); button.classList.toggle("done"); toast(button.classList.contains("done") ? "Topic marked complete" : "Topic marked incomplete"); })); }
function bookmarks() { const ids = getSaved("mtech-compass-bookmarks"); const courses = state.data.courses.filter(c => ids.includes(courseId(c))); layout(`${breadcrumb([{label:"Saved courses"}])}<p class="eyebrow">Your short list</p><h1 class="page-title">Saved courses</h1><p class="page-description">Keep the subjects you return to most within easy reach.</p><div class="course-list" style="margin-top:30px">${courses.length ? courses.map(courseCard).join("") : `<p class="empty">Nothing saved yet. Use the ☆ button on any course to build your short list.</p>`}</div>`, "bookmarks"); }
function notFound(){ layout(`<section class="empty"><p class="eyebrow">404</p><h1 class="page-title">This path isn’t on the map.</h1><p><a class="button" href="#/">Go home</a></p></section>`); }
function render() { const path = location.hash.slice(1) || "/"; const parts = path.split("/").filter(Boolean); if (!parts.length) home(); else if (parts[0] === "library") library(); else if (parts[0] === "semester") library(parts[1]); else if (parts[0] === "course") coursePage(parts[1]); else if (parts[0] === "bookmarks") bookmarks(); else notFound(); }
async function init() { try { const res = await fetch(DATA_URL); if (!res.ok) throw new Error("Could not load the syllabus registry"); state.data = await res.json(); document.body.classList.toggle("auto-dark", localStorage.getItem("mtech-compass-theme") === "dark"); render(); } catch (error) { $("#app").innerHTML = `<p class="empty">${error.message}. Start this site through a local server so it can read the prep data.</p>`; } }
$("#theme-toggle").addEventListener("click", () => { const dark = !document.body.classList.contains("auto-dark"); document.body.classList.toggle("auto-dark",dark); localStorage.setItem("mtech-compass-theme",dark ? "dark" : "light"); });
window.addEventListener("hashchange", render); init();
